# Name of website
title: Natura11y Inclusive Framwork
# Short description of your site
description: An open source accessible design system

# URL (Local)
baseurl: ''

# Archive (Append '/version/x.x')
# baseurl: '/nyc-core-framework/version/1.5'

# Permalinks
permalink: pretty

# Exclude
exclude:
  - readme.md

  # Comment (exclude) for versioning
  # - version/*`

  - src/*
  - .babelrc
  - node_modules/*
  - Gemfile
  - Gemfile.lock
  - nyc-core-framework.code-workspace
  - package-lock.json
  - package.json
  - webpack.config.js

# Collections
collections:
  docs-introduction:
    output: true
    permalink: /docs/:path/
    order:
      - get-started.html
      - customization.html
      - accessibility.html

  docs-a-z:
    output: true
    permalink: /docs/:path/

  example-pages:
    output: true
    permalink: /examples/:slug.html

# Custom Global Vars

cdn_url_css: 'https://cdn.jsdelivr.net/gh/cavidano/natura11y@main/dist/css/natura11y.css'
cdn_url_js: 'https://cdn.jsdelivr.net/gh/cavidano/natura11y@main/dist/js/natura11y.js'
cdn_url_icons: 'https://cdn.jsdelivr.net/gh/cavidano/natura11y-icons@1.0.0/dist/css/natura11y_icons.css'

example-custom-properties: ' style="
  --primary: #ffcc66;
  --secondary: #591650;
  --dark: #1a1a33;
  --light: #ede7e2;
  --primary-text: var(--dark);
  --secondary-text: white;
  --body-font-family: Source Sans Pro ;
  --body-font-size: 22px;
  --body-line-height: 1.4;"
  data-example
  '
